### ISSUE TITLE
Highlighting in preview mode

### ISSUE THREAD

**Issue by FALLAI-Denis** [mjbvz/vscode-fenced-code-block-grammar-injection-example#20] opened 2024-07-21 19:06 UTC
Hi,

I successfully implemented your solution for COBOL language, but the preview display does not work...
Is there anything special I need to do or something I forgot to implement?

![image](https://github.com/user-attachments/assets/4e28f20a-233b-4e3c-bcbc-fb3f876fdc63)

![image](https://github.com/user-attachments/assets/31b669bf-64e5-439a-a259-7ef0c035b6e9)

More information on the GitHub site of the supplier of the COBOL grammar used: https://github.com/IBM/zopeneditor-about/issues/428

Thanks.

**Comment by mjbvz** [comment] 2024-07-22 15:40
Duplicate of #17

**Closed as completed by mjbvz** 2024-07-22 15:40 UTC
